//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Demand()
        {
            this.DemandItems = new HashSet<DemandItem>();
        }
    
        public int ID { get; set; }
        public System.DateTime DemandDate { get; set; }
        public int CustomerID { get; set; }
        public int WarhouseID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Warhouse Warhouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemandItem> DemandItems { get; set; }
    }
}
