//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        public int ID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime DemandDate { get; set; }
        public int ItemCode { get; set; }
        public int SupplierID { get; set; }
        public int WarhouseID { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public System.DateTime Expiry { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Warhouse Warhouse { get; set; }
    }
}
